# Generated by Django 3.0.5 on 2020-04-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20190716_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='description',
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='status',
            field=models.CharField(choices=[('student', 'student'), ('employee', 'employee'), ('administration', 'administration')], default='student', max_length=15),
        ),
    ]
