# Generated by Django 3.0.5 on 2020-05-05 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20200430_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='myprofile',
            name='acc_type',
            field=models.CharField(choices=[('student', 'student'), ('page', 'page')], default='student', max_length=10),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='branch',
            field=models.CharField(choices=[('IT', 'IT'), ('COE', 'COE'), ('ECE', 'ECE'), ('EE', 'EE'), ('SE', 'SE'), ('ENE', 'ENE'), ('PCT', 'PCT'), ('MCE', 'MCE'), ('BT', 'BT'), ('EP', 'EP'), ('AE', 'AE'), ('CE', 'CE'), ('ME', 'ME'), ('PIE', 'PIE')], default='IT', max_length=15),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='fname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='lname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='societies',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('prefer not to say', 'prefer not to say')], default='prefer not to say', max_length=20),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcomments', to='social.MyPost'),
        ),
    ]
